server:
  port: 5001

spring:
  datasource:
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql.BasicBinder: TRACE

